# Generated by Django 5.1.1 on 2024-09-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('vaga', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Nome da Vaga')),
                ('em_uso', models.BooleanField(default=False, verbose_name='Vaga em uso')),
            ],
            options={
                'verbose_name': 'Cadastro de Vaga',
                'verbose_name_plural': 'Cadastro de Vagas',
                'ordering': ['vaga'],
            },
        ),
        migrations.CreateModel(
            name='historico_Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=8, null=True, verbose_name='Placa do Veiculo')),
                ('horario_Entrada', models.DateTimeField(verbose_name='Data e Hora de Entrada')),
                ('horario_Saida', models.DateTimeField(verbose_name='Data e Hora de Saida')),
                ('tempo_Estacionado', models.DurationField(blank=True, editable=False, null=True, verbose_name='Tempo Estacionado')),
                ('vaga_Ocupada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vagas')),
            ],
            options={
                'verbose_name': 'Historico do Estacionamento',
                'verbose_name_plural': 'Historico do Estacionamento',
                'ordering': ['-horario_Entrada'],
            },
        ),
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=8, null=True, verbose_name='Placa do Veiculo')),
                ('horario_Entrada', models.DateTimeField(verbose_name='Data e Hora de Entrada')),
                ('horario_Saida_Estimada', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Saída Estimada')),
                ('horario_Saida', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data e Hora de Saída')),
                ('vaga_Ocupada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vagas')),
            ],
            options={
                'verbose_name': 'Estacionamento',
                'verbose_name_plural': 'Estacionamento',
                'ordering': ['-horario_Entrada'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('horario_Saida__isnull', True)), fields=('vaga_Ocupada',), name='A vaga atualmente esta ocupada')],
            },
        ),
    ]
